server:
  port: 8080
  servlet:
    context-path: /materils_v2.0/
mybatis:
  type-aliases-package: com.example.entity
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sdms?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    
    username: root
    password: 1014
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        #最大空闲连接
        max-idle: 8
        #最大阻塞等待时间(负值表示无限制)
        max-wait: -1
        #最大连接数
        max-active: 8
        min-idle: 0
    #连接超时时间
    timeout: 5000
